# Instead of using artifacts, just build in an NFS-mounted directory,
# $BUILD_DIR, that's unique to each pipeline in case there are concurrent
# pipelines.  Why not use artifacts?
#
# - LLVM's build directory is huge.  For me, it's 46G when including just
#   the clang and openmp subprojects, which are required for Clacc, and it's
#   85G when including nearly all subprojects.
# - At this size, it takes a long time to upload/download between stages and
#   can be rejected as an upload because of its size.  For me, it added 20
#   min to the already 30 min build of that 46G and then was rejected.
# - Artifacts are posted for download and stored long past when it's useful
#   for humans to download the LLVM build directory, which is typically
#   never.
# - We could squash the pipeline to one stage to avoid the need for
#   artifacts, but pipeline stages are a convenient way to view results when
#   debugging.
#
# The NFS solution used here is based on the following comment (which is in
# response to a proposal for a gitlab feature that would solve this
# problem):
#
#   https://gitlab.com/gitlab-org/gitlab/issues/29265#note_225288132
#
# However, because the NFS-mounted build directory name is different for each
# pipeline, ccache misses if we compile within it.  Thus, we set
# CCACHE_NOHASHDIR and CCACHE_BASEDIR (neither alone proves sufficient), as
# suggested by the ccache manual.  CCACHE_NOHASHDIR can lead to incorrect
# directory names in debugging symbols, but currently we don't expect those to
# matter to our CI builds.
variables:
  BUILD_DIR_PROJ: $CI_BUILDS_DIR/$CI_PROJECT_PATH_SLUG-builds
  BUILD_DIR: $CI_BUILDS_DIR/$CI_PROJECT_PATH_SLUG-builds/$CI_PIPELINE_ID-$BUILD_ID
  BUILD_DIRS: $CI_BUILDS_DIR/$CI_PROJECT_PATH_SLUG-builds/$CI_PIPELINE_ID-*
  LLVM_CCACHE_PARAMS: 'CCACHE_CPP2=yes CCACHE_NOHASHDIR=yes CCACHE_BASEDIR=$CI_BUILDS_DIR/$CI_PROJECT_PATH_SLUG-builds'
  XFAIL_COMMON:
    offloading/memory_manager.cpp
    offloading/parallel_offloading_map.cpp

stages:
  - setup
  - config
  - build
  - test
  - cleanup
  - manual cleanup

#-------------------------------------------------
# build configurations
#
# Test every architecture with a debug build (thus checking assertions) using
# python3.  There are many kolds, so use them to check configuration choices
# that are hopefully orthogonal to the architecture.
#-------------------------------------------------

.leconte:
  tags: [shell, leconte]
  variables:
    BUILD_ID: leconte
    MODULES: cmake/3.19.2 gnu/9.2.0 nvhpc/21.2
    CMAKE: cmake
    NINJA: ninja
    PYTHON: /usr/bin/python3
    CMAKE_BUILD_TYPE: Debug
    CMAKE_OFFLOAD_CONFIG:
      -DCLANG_OPENMP_NVPTX_DEFAULT_ARCH=sm_70
      -DCLANG_ACC_TEST_EXE_X86_64=0
      -DCLANG_ACC_TEST_EXE_PPC64LE=4
      -DCLANG_ACC_TEST_EXE_NVPTX64=6
      -DLIBOMPTARGET_NVPTX_COMPUTE_CAPABILITIES=70
    PATH_PREPEND:
      /opt/nvidia/hpc_sdk/Linux_ppc64le/21.2/cuda/11.0/bin
    XFAIL:
      Driver/openmp-offload-gpu.c

.kold:
  tags: [shell, kold]
  variables:
    BUILD_ID: kold
    MODULES: gnu/9.1.0
    CMAKE: cmake3
    NINJA: ninja-build
    PYTHON: /usr/bin/python3
    CMAKE_BUILD_TYPE: Debug
    CMAKE_OFFLOAD_CONFIG:
      -DCLANG_ACC_TEST_EXE_X86_64=4
      -DCLANG_ACC_TEST_EXE_PPC64LE=0
      -DCLANG_ACC_TEST_EXE_NVPTX64=0
    PATH_PREPEND:
      ""
    XFAIL:
      offloading/bug49334.cpp
      ompt/tasks/task_if0-depend.c

# Sometimes bugs cause only release builds to fail.  For example, debugging
# macros might accidentally be used but not defined in release builds.
.release:
  extends: [.kold]
  variables:
    BUILD_ID: release
    CMAKE_BUILD_TYPE: Release
    XFAIL:
      CodeGen/AMDGPU/GlobalISel/irtranslator-call-implicit-args.ll
      CodeGen/AMDGPU/GlobalISel/irtranslator-call-return-values.ll
      CodeGen/AMDGPU/GlobalISel/irtranslator-call-sret.ll
      CodeGen/AMDGPU/GlobalISel/irtranslator-call.ll
      CodeGen/AMDGPU/GlobalISel/irtranslator-indirect-call.ll
      CodeGen/AMDGPU/agpr-register-count.ll
      CodeGen/AMDGPU/call-argument-types.ll
      CodeGen/AMDGPU/call-constant.ll
      CodeGen/AMDGPU/call-graph-register-usage.ll
      CodeGen/AMDGPU/call-preserved-registers.ll
      CodeGen/AMDGPU/call-waitcnt.ll
      CodeGen/AMDGPU/cc-update.ll
      CodeGen/AMDGPU/cross-block-use-is-not-abi-copy.ll
      CodeGen/AMDGPU/indirect-call.ll
      CodeGen/AMDGPU/returnaddress.ll
      CodeGen/AMDGPU/spill-csr-frame-ptr-reg-copy.ll
      CodeGen/AMDGPU/stack-realign.ll
      CodeGen/AMDGPU/unstructured-cfg-def-use-issue.ll
      CodeGen/AMDGPU/vgpr-tuple-allocation.ll
      CodeGen/MIR/AMDGPU/machine-function-info-no-ir.mir
      offloading/bug49334.cpp

# Not setup or cleanup.
.non-utility:
  dependencies: []
  variables:
    GIT_STRATEGY: none
  before_script:
    - echo $MODULES
    - module load $MODULES
    - echo $PATH_PREPEND
    - if test x"$PATH_PREPEND" != x; then PATH="$PATH_PREPEND:$PATH"; fi
    - echo $PATH
    - pwd
    - echo $BUILD_DIR
    - cd $BUILD_DIR/build
  after_script:
    - echo "$LLVM_CCACHE_PARAMS"
    - env $LLVM_CCACHE_PARAMS ccache -sp
    - du -hs $BUILD_DIR/build

#-------------------------------------------------
# setup
#-------------------------------------------------

.setup:
  stage: setup
  script:
    - pwd
    - echo $BUILD_DIR_PROJ
    # Try to remove anything older than 6 hours that was left by a previous
    # pipeline for this project.  Doing this in the setup stage instead of
    # cleanup stage ensures that it runs before a new job even if prior jobs
    # failed or were canceled.  git clone creates files with old modification
    # times, so check file creation time (-cmin) instead.
    - find $BUILD_DIR_PROJ -cmin +360 -delete || true
    - mkdir -p $BUILD_DIR_PROJ
    - echo $BUILD_DIR
    # Remove this build config's build directory if it already exists.  It
    # might exist if, for example, this setup job previously failed due to a
    # transient Gitlab/ExCL problem.
    - rm -rf $BUILD_DIR
    - mkdir $BUILD_DIR
    - mkdir $BUILD_DIR/build
    # Clone the runner's git clone into the NFS-mounted build directory.  We
    # cannot use the runner's git clone directly because its location relative
    # to the build directory varies across runners, and that would cause ccache
    # to miss whenever the runner changes no matter how we set CCACHE_BASEDIR.
    # We've also tried creating a symlink to the runner's git clone at the
    # start of every job, but that causes ccache to miss in the same manner, so
    # apparently the symlink is expanded somewhere.
    - git --version
    - time git clone `pwd` $BUILD_DIR/source

leconte (setup):
  extends: [.leconte, .setup]

kold (setup):
  extends: [.kold, .setup]

release (setup):
  extends: [.release, .setup]

#-------------------------------------------------
# cleanup
#-------------------------------------------------

.rm-build-dir:
  variables:
    GIT_STRATEGY: none
  script:
    - pwd
    - echo $BUILD_DIR
    - rm -rf $BUILD_DIR
    - rmdir $BUILD_DIR_PROJ || true

.cleanup:
  stage: cleanup
  extends: .rm-build-dir

.manual-cleanup:
  stage: manual cleanup
  extends: .rm-build-dir
  when: manual
  needs: []

leconte (cleanup):
  extends: [.leconte, .cleanup]
  needs:
    - job: leconte (test)
      artifacts: false

kold (cleanup):
  extends: [.kold, .cleanup]
  needs:
    - job: kold (test)
      artifacts: false

release (cleanup):
  extends: [.release, .cleanup]
  needs:
    - job: release (test)
      artifacts: false

leconte (manual cleanup):
  extends: [.leconte, .manual-cleanup]

kold (manual cleanup):
  extends: [.kold, .manual-cleanup]

release (manual cleanup):
  extends: [.release, .manual-cleanup]

z-cleanup-pipeline-builds:
  stage: manual cleanup
  when: manual
  needs: []
  tags: [shell, kold]
  variables:
    GIT_STRATEGY: none
  script:
    - echo $BUILD_DIRS
    - rm -rf $BUILD_DIRS

z-cleanup-project-builds:
  stage: manual cleanup
  when: manual
  needs: []
  tags: [shell, kold]
  variables:
    GIT_STRATEGY: none
  script:
    - echo $BUILD_DIR_PROJ
    - rm -rf $BUILD_DIR_PROJ

#-------------------------------------------------
# config
#-------------------------------------------------

.config:
  extends: .non-utility
  stage: config
  script:
    - echo $CMAKE
    - $CMAKE --version
    - echo $CMAKE_BUILD_TYPE
    - echo $GCC_DIR
    - echo $PYTHON
    - $PYTHON --version
    - echo $LLVM_CCACHE_PARAMS
    - echo $CMAKE_OFFLOAD_CONFIG
    - time $CMAKE -G Ninja
                  -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE
                  -DLLVM_CCACHE_BUILD=ON
                  -DLLVM_USE_SPLIT_DWARF=true
                  -DLLVM_USE_LINKER=gold
                  -DCMAKE_C_COMPILER=gcc
                  -DCMAKE_CXX_COMPILER=g++
                  -DGCC_INSTALL_PREFIX=$GCC_DIR
                  -DLLVM_ENABLE_PROJECTS='clang'
                  -DLLVM_ENABLE_RUNTIMES='openmp'
                  -DPython3_EXECUTABLE=$PYTHON
                  -DLLVM_CCACHE_PARAMS="$LLVM_CCACHE_PARAMS"
                  -DLLVM_LIT_ARGS='-s -vv'
                  $CMAKE_OFFLOAD_CONFIG
                  ../source/llvm
      |& tee $CI_PROJECT_DIR/cmake-log.txt
    - cp CMakeCache.txt $CI_PROJECT_DIR
  artifacts:
    when: always
    paths: [cmake-log.txt, CMakeCache.txt]

leconte (config):
  extends: [.leconte, .config]
  needs:
    - job: leconte (setup)
      artifacts: false

kold (config):
  extends: [.kold, .config]
  needs:
    - job: kold (setup)
      artifacts: false

release (config):
  extends: [.release, .config]
  needs:
    - job: release (setup)
      artifacts: false

#-------------------------------------------------
# build
#-------------------------------------------------

.build:
  extends: .non-utility
  stage: build
  script:
    - echo $NINJA
    - $NINJA --version
    - time $NINJA -l `nproc` |& tee $CI_PROJECT_DIR/build-log.txt
  artifacts:
    when: always
    paths: [build-log.txt]

leconte (build):
  extends: [.leconte, .build]
  needs:
    - job: leconte (config)
      artifacts: false

kold (build):
  extends: [.kold, .build]
  needs:
    - job: kold (config)
      artifacts: false

release (build):
  extends: [.release, .build]
  needs:
    - job: release (config)
      artifacts: false

#-------------------------------------------------
# tests
#
# The additional build required for the test suite can be very noisy and
# exceed the log output limit.  Run that first, grep for key text, and
# make the full version an artifact.
#
# When there are fails, the test suite run can be very noisy too and
# exceed the log output limit.  It's hard to grep for just the important
# stuff, so just print it all but also dump to an artifact.
#
# At various points in LLVM's history, check-all has run multiple lit
# invocations.  For example, at the time of this writing, specifying runtimes
# like openmp in LLVM_ENABLE_RUNTIMES instead of in LLVM_ENABLE_PROJECTS causes
# all such runtimes' test suites to run in a separate lit invocation from all
# other projects' test suites.  As a result, if a runtime test fails, then the
# other projects' test suites don't run.  The best solution is to fix check-all,
# but that won't protect us from unknowingly missing test results the next time
# this happens.  The following use of --ignore-fail followed by grep avoids that
# problem.  The count printed by grep tells us how many test suite summaries we
# need to search for.
#-------------------------------------------------

.test:
  extends: .non-utility
  stage: test
  script:
    - echo $CHECK_TARGETS
    - echo $NINJA
    - $NINJA --version
    - echo "$XFAIL_COMMON" "$XFAIL" | sed 's/  */;/g' | tee xfail.txt
    - time LIT_OPTS='--filter=xxxxxxxxx --allow-empty-runs'
           $NINJA -l `nproc` check-all
      |& tee $CI_PROJECT_DIR/check-all-build-log.txt
      | grep '^\[[0-9]\+/[0-9]\+]\|\<error:'
    - time FILECHECK_OPTS='-dump-input-filter=all -vv -color'
           LIT_OPTS="--xunit-xml-output $CI_PROJECT_DIR/check-all.xml --xfail=`cat xfail.txt` --ignore-fail"
           $NINJA -l `nproc` check-all
      |& tee $CI_PROJECT_DIR/check-all-log.txt
    - "! grep -c \"'--ignore-fail' was specified\"
                 $CI_PROJECT_DIR/check-all-log.txt"
  artifacts:
    when: always
    paths: [check-all-build-log.txt, check-all-log.txt, check-all.xml]
    reports:
      junit: check-all.xml

leconte (test):
  extends: [.leconte, .test]
  needs:
    - job: leconte (build)
      artifacts: false

kold (test):
  extends: [.kold, .test]
  needs:
    - job: kold (build)
      artifacts: false

release (test):
  extends: [.release, .test]
  needs:
    - job: release (build)
      artifacts: false
